# For more information: https://laravel.com/docs/sail
version: '3'
services:
    
    # Server
    nginx:
        image: nginx:stable-alpine
        container_name: fbs_nginx
        ports:
            - "8000:80"
        links:
            - php
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
            - ./docker/logs/nginx:/ar/logs/nginx:rw
        depends_on:
            - php
            - mysql
        networks:
            - sail

    # Database
    mysql:
        image: mysql:5.7.22
        container_name: fbs_mysql
        restart: unless-stopped
        tty: true
        ports:
            - "5010:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: fbs
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - sail

    # PHP Service
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: fbs_php
        volumes:
            - ./:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - sail

    # laravel.test:
    #     build:
    #         context: ./vendor/laravel/sail/runtimes/8.1
    #         dockerfile: Dockerfile
    #         args:
    #             WWWGROUP: '${WWWGROUP}'
    #     image: sail-8.1/app
    #     extra_hosts:
    #         - 'host.docker.internal:host-gateway'
    #     ports:
    #         - '${APP_PORT:-80}:80'
    #         - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    #     environment:
    #         WWWUSER: '${WWWUSER}'
    #         LARAVEL_SAIL: 1
    #         XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
    #         XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    #     volumes:
    #         - '.:/var/www/html'
    #     networks:
    #         - sail
networks:
    sail:
